### PR TITLE
Add geojson clipped to coastline

### PR DESCRIPTION
**Pull request by larsga**
Adding this file should solve issue #2

### CODE REVIEW

**Comment by atlefren** [comment]
Ah, at last!

What kind of geometry have you used for the coastlines? They seem to be a bit coarse or off? 

Take "Strandebarm" for example:

image

**Comment by larsga** [comment]
I used [Natural Earth](https://www.naturalearthdata.com/), since it's the only thing I have. If you have a better source for the Norwegian coastline I'd be happy to use that instead.

**Comment by atlefren** [comment]
I'll check if I can find any appropriately licensed datasets with better data. But this is still better than nothing, so I think it's best to merge it for now?

**Comment by larsga** [comment]
Would be great if you could check.

I'm using this dataset and am very happy with it. So I think if you're OK with it, then you should just go ahead and merge. (Leaving the actual merging to you.)

**Comment by larsga** [comment]
👍

**Pull request merged**
